services:

  frontend: # Next.js UI
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8080}
    container_name: frontend
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - core
    networks:
      - backend

  core: # основной API сервис: auth, проекты, репозитории
    build:
      context: .
      args:
        SERVICE: core
    container_name: core
    env_file:
      - config/.core.env
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      pg:
        condition: service_healthy
      nats:
        condition: service_healthy
    networks:
      - backend

  webhook: # принимает события от GitHub и публикует их в NATS
    build:
      context: .
      args:
        SERVICE: webhook
    container_name: webhook
    env_file:
      - config/.webhook.env
    ports:
      - "127.0.0.1:2602:2602"
    depends_on:
      pg:
        condition: service_healthy
      nats:
        condition: service_healthy
    networks:
      - backend

  coordinator: # читает события из NATS и управляет жизненным циклом джоб
    build:
      context: .
      args:
        SERVICE: coordinator
    container_name: coordinator
    env_file:
      - config/.coordinator.env
    depends_on:
      pg:
        condition: service_healthy
      nats:
        condition: service_healthy
    networks:
      - backend

  builder: # выполняет сборку: клонирует репо, собирает docker образ, сохраняет артефакт в MinIO
    build:
      context: .
      args:
        SERVICE: builder
    container_name: builder
    env_file:
      - config/.builder.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # доступ к docker daemon хоста для сборки образов
    depends_on:
      nats:
        condition: service_healthy
      s3:
        condition: service_healthy
    networks:
      - backend

  deployer: # выполняет деплой: забирает артефакт из MinIO, заливает на сервер по SSH и запускает restart-команду
    build:
      context: .
      args:
        SERVICE: deployer
    container_name: deployer
    env_file:
      - config/.deployer.env
    depends_on:
      nats:
        condition: service_healthy
      s3:
        condition: service_healthy
    networks:
      - backend

  pg: # хранит пользователей, проекты, историю сборок и метаданные
    image: postgres:14-alpine
    container_name: postgresql
    env_file:
      - config/.pg.env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck: # для depends_on service_healthy
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nats: # гарантированная доставка событий и данных
    image: nats:2.10-alpine
    container_name: nats-jetstream
    ports:
      - "127.0.0.1:4222:4222"
      - "127.0.0.1:8222:8222"
    volumes:
      - nats_data:/var/lib/nats-js/data
    command: "-js -sd /var/lib/nats-js/data -m 8222 --name nats-1" # команда для указания волюма и запуска в режиме jetstream
    networks:
      - backend
    healthcheck: # для depends_on service_healthy
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8222 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  nats-box: # nats cli для управления стримами из консоли
    image: natsio/nats-box:0.19.2
    container_name: nats-cli
    env_file:
      - config/.nats.env
    depends_on:
      nats:
        condition: service_healthy
    command: sleep infinity # loop чтобы контейнер не падал, и мы могли зайти внутрь
    networks:
      - backend

  s3: # хранение артефактов
    image: minio/minio:latest
    container_name: minio
    ports:
      - "127.0.0.1:9000:9000" # для доступа к хранилищу
      - "127.0.0.1:9001:9001" # для доступа к админке
    env_file:
      - config/.minio.env
    volumes:
      - minio_data:/var/lib/minio/data
    command: 'server /var/lib/minio/data --console-address ":9001"' # задаем путь волюма и порт для админки
    networks:
      - backend
    healthcheck: # для depends_on service_healthy
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  backend:

volumes:
  nats_data:
  postgres_data:
  minio_data:

